### ISSUE TITLE
composer file

### ISSUE THREAD

**Issue by jajouka79** [stevenmaguire/toran#1]
thanks for this repo, I've almost got it working, tp is on my server and i have added my private repos in the tp admin, i've altered to composer json file as instructed. but i can't see how i list the packages in the composer.json file, whats the type etc.? should i require them? thanks

**Comment by stevenmaguire** [comment]
Have you reviewed [the documentation](https://getcomposer.org/doc/articles/handling-private-packages-with-satis.md)?

**Comment by jajouka79** [comment]
yes i have read over the docs. i am trying to set up packages, with this code in my composer.json file:

    {
      "type": "composer", 
      "url": "http://toran.local/app.php/repo/packagist/"
    },
    {
      "packagist": false
    }

I have two packages set up in toran proxy but on composer install i get this error:

  [Seld\JsonLint\ParsingException]                                                       
  "http://toran.local/app.php/repo/packagist/packages.json" does not contain valid JSON  
  Parse error on line 1:                                                                 
  <br /><b>Warning</b                                                                    
  ^                                                                                      
  Expected one of: 'STRING', 'NUMBER', 'NULL', 'TRUE', 'FALSE', '{', '['  

private repositories are working its just packagist packages that are not

**Comment by stevenmaguire** [comment]
Can you share your whole package.json file?

**Comment by jajouka79** [comment]
{"notify-batch":"https:\/\/packagist.org\/downloads\/","providers-url":"\/p\/%package%$%hash%.json","search":"https:\/\/packagist.org\/search.json?q=%query%","mirrors":[{"dist-url":"http:\/\/toran.local\/repo\/packagist\/dists\/%package%\/%version%\/%reference%.%type%","preferred":true}],"providers-lazy-url":"\/repo\/packagist\/p\/%package%.json"}

**Comment by stevenmaguire** [comment]
Is this file used as a template? Is it rendered with dynamic data?

**Comment by jajouka79** [comment]
this is auto-generated by toran proxy

its stored here : 

/var/www/toran.local/app/toran/cache/packagist/p

**Comment by jajouka79** [comment]
my composer.json file is :+1: 

  {
    "repositories": [ 
    {
      "type": "composer",
      "url": "http://wpackagist.org"
    },
    {
      "type": "composer", 
      "url": "http://toran.local/app.php/repo/private/"
    },
    {
      "type": "composer", 
      "url": "http://toran.local/app.php/repo/packagist/"
    },
    {
      "packagist": false
    }
  ],
  "minimum-stability": "dev",
  "prefer-stable": true,
  "require": {
    "php": ">=5.4",
    "composer/installers": "~1.0.12",
    "wpplex/wp-options": "*"
  }
}

**Comment by stevenmaguire** [comment]
Your composer file does pass composer's minimum validation and encourages definition of more properties, similar to the composer.json in this project. 

```bash
./composer.json is valid for simple usage with composer but has
strict errors that make it unable to be published as a package:
See http://getcomposer.org/doc/04-schema.md for details on the schema
name : is missing and it is required
description : is missing and it is required
No license specified, it is recommended to do so. For closed-source software you may use "proprietary" as license.
require.wpplex/wp-options : unbound version constraints (*) should be avoided
```

The error appears to be related to you local environment. I don't know how much I can help there.

**Comment by jajouka79** [comment]
i have tried many different composer.json files

here is another one


{
  "name": "sietest/project1",
  "type": "project",
  "config": {
    "preferred-install": "dist",
    "generate-salts": true
  },
  "autoload": {
    "psr-4": {"Roots\\Bedrock\\": "scripts/Roots/Bedrock"}
  },
  "scripts": {
    "post-root-package-install": ["Roots\\Bedrock\\Installer::addSalts"]
  },
  "repositories": [ 
    {
      "type": "composer",
      "url": "http://wpackagist.org"
    },
    {
      "type": "composer", 
      "url": "http://toran.local/app.php/repo/private/"
    },
    {
      "type": "composer", 
      "url": "http://toran.local/app.php/repo/packagist/"
    },
    {
      "packagist": false
    }
  ],
  "minimum-stability": "dev",
  "prefer-stable": true,
  "require": {
    "php": ">=5.4",
    "composer/installers": "~1.0.12",
    "jajouka/medusa_custom_meta_boxes": "*@dev",
    "jajouka79/cmb-field-select2": "*",
    "jajouka79/cmb2-attached-posts": "*",
    "jajouka79/cmb-field-map": "*",
    "jajouka79/cmb-field-gallery": "*",
    "wpplex/wp-options": "*"
  },
  "extra": {
    "installer-paths": {
      "web/app/mu-plugins/{$name}/": ["type:wordpress-muplugin"],
      "web/app/plugins/{$name}/": ["type:wordpress-plugin"],
      "web/app/themes/{$name}/": ["type:wordpress-theme"]
    },
    "wordpress-install-dir": "web/wp"
  }
}

**Comment by stevenmaguire** [comment]
This thing is a mess!

The PSR definitions were missing escaping backlashes, those are corrected below. Additionally, there are a number of composer validation problems.

You can run a command to validate these composer files; it helps. Run this command in the directory with your composer.json.

```bash
$ composer validate
```

```bash
./composer.json is invalid, the following errors/warnings were found:
require.jajouka79/cmb-field-select2 : invalid version constraint (Could not parse version constraint : Invalid version string "")
require.jajouka79/cmb2-attached-posts : invalid version constraint (Could not parse version constraint : Invalid version string "")
require.jajouka79/cmb-field-map : invalid version constraint (Could not parse version constraint : Invalid version string "")
require.jajouka79/cmb-field-gallery : invalid version constraint (Could not parse version constraint : Invalid version string "")
require.wpplex/wp-options : invalid version constraint (Could not parse version constraint : Invalid version string "")
description : is missing and it is required
No license specified, it is recommended to do so. For closed-source software you may use "proprietary" as license.
require.jajouka/medusa_custom_meta_boxes : unbound version constraints (@dev) should be avoided
```

```json
{
   "name":"sietest/project1",
   "type":"project",
   "config":{
      "preferred-install":"dist",
      "generate-salts":true
   },
   "autoload":{
      "psr-4":{
         "Roots\\Bedrock\\": "         scripts/Roots/Bedrock"
      }
   },
   "scripts":{
      "post-root-package-install":[
         "Roots\\Bedrock\\Installer::addSalts"
      ]
   },
   "repositories":[
      {
         "type":"composer",
         "url":"http://wpackagist.org"
      },
      {
         "type":"composer",
         "url":"http://toran.local/app.php/repo/private/"
      },
      {
         "type":"composer",
         "url":"http://toran.local/app.php/repo/packagist/"
      },
      {
         "packagist":false
      }
   ],
   "minimum-stability":"dev",
   "prefer-stable":true,
   "require":{
      "php":">=5.4",
      "composer/installers":"~1.0.12",
      "jajouka/medusa_custom_meta_boxes":"@dev",
      "jajouka79/cmb-field-select2":"",
      "jajouka79/cmb2-attached-posts":"",
      "jajouka79/cmb-field-map":"",
      "jajouka79/cmb-field-gallery":"",
      "wpplex/wp-options":""
   },
   "extra":{
      "installer-paths":{
         "web/app/mu-plugins/{$name}/":[
            "type:wordpress-muplugin"
         ],
         "web/app/plugins/{$name}/":[
            "type:wordpress-plugin"
         ],
         "web/app/themes/{$name}/":[
            "type:wordpress-theme"
         ]
      },
      "wordpress-install-dir":"web/wp"
   }
}
```

**Comment by jajouka79** [comment]
i dont think its the composer.json schema as i have tried many different versions with different projects. toran proxy private repos work fine but packagist packages dont work

**Comment by stevenmaguire** [comment]
This package is my fork from the toran project and I don't know how else to help with your problem. Perhaps you could try to address the problem with someone closer to the toran project.

**Comment by jajouka79** [comment]
ok, thanks anyway

**Comment by stevenmaguire** [comment]
Good luck!
